/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-03-29 05:43:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._0324;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class requestpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/mystyle.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("	$('#lprod').on('click',function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"http://localhost/jqpro/0324/LprodController.jsp\",\r\n");
      out.write("			type : \"get\",\r\n");
      out.write("			success : function(res){\r\n");
      out.write("				alert(\"성공\");\r\n");
      out.write("				\r\n");
      out.write("				code = \"<table border='1'>\"\r\n");
      out.write("				code += \"<tr>\"\r\n");
      out.write("				code += \"<td>아이디</td>\"\r\n");
      out.write("				code += \"<td>분류코드</td>\"\r\n");
      out.write("				code += \"<td>상품종류</td>\"\r\n");
      out.write("				code += \"</tr>\"\r\n");
      out.write("				$(res).each(function(i,v){\r\n");
      out.write("					code += \"<tr>\"\r\n");
      out.write("					code += \"<td>\" + res[i].lprod_id + \"</td>\"\r\n");
      out.write("					code += \"<td>\" + res[i].lprod_gu + \"</td>\"\r\n");
      out.write("					code += \"<td>\" + v.lprod_nm + \"</td>\"\r\n");
      out.write("					code += \"</tr>\"\r\n");
      out.write("				})\r\n");
      out.write("				code += \"</table>\"\r\n");
      out.write("				\r\n");
      out.write("				$('#result1').html(code);\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr){\r\n");
      out.write("				alert(\"상태 : \" + xhr.status);\r\n");
      out.write("			},\r\n");
      out.write("			dataType : 'json'\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$('#buyer').on('click', function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"http://localhost/jqpro/0324/BuyerController.jsp\",\r\n");
      out.write("			type : \"get\",\r\n");
      out.write("			success : function(res){\r\n");
      out.write("				alert(\"성공\");\r\n");
      out.write("				\r\n");
      out.write("				code = \"\";\r\n");
      out.write("				$(res).each(function(i,v){\r\n");
      out.write("					code += \"<p>\" + res[i].buyer_id + \"  \" + res[i].buyer_name + \"</p>\";\r\n");
      out.write("				})\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				$('#td1').html(code);\r\n");
      out.write("				\r\n");
      out.write("				$('p').on('click',function(){\r\n");
      out.write("					text = $(this).text();\r\n");
      out.write("					id = text.substr(0,6);\r\n");
      out.write("// 					alert(id);\r\n");
      out.write("					\r\n");
      out.write("					// jsp String??\r\n");
      out.write("\r\n");
      out.write("// 					String id = \"P10101\";\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url : \"http://localhost/jqpro/0324/BuyerController2.jsp\",\r\n");
      out.write("						type : \"get\",\r\n");
      out.write("						data : {id : id},\r\n");
      out.write("						success : function(res){\r\n");
      out.write("// 							alert(\"클릭성공\");\r\n");
      out.write("							\r\n");
      out.write("							code = \"\";\r\n");
      out.write("							code += \"<p>BUYER_ID       : \" + res.buyer_id + \"</p>\";\r\n");
      out.write("							code += \"<p>BUYER_NAME     : \" + res.buyer_name + \"</p>\";\r\n");
      out.write("							code += \"<p>BUYER_LGU      : \" + res.buyer_lgu + \"</p>\";\r\n");
      out.write("							code += \"<p>BUYER_BANK     : \" + res.buyer_bank + \"</p>\";\r\n");
      out.write("							code += \"<p>BUYER_BANKNO   : \" + res.buyer_bankno + \"</p>\";\r\n");
      out.write("							code += \"<p>BUYER_BANKNAME : \" + res.buyer_bankname + \"</p>\";\r\n");
      out.write("							code += \"<p>BUYER_ZIP      : \" + res.buyer_zip + \"</p>\";\r\n");
      out.write("							code += \"<p>BUYER_ADD1     : \" + res.buyer_add1 + \"</p>\";\r\n");
      out.write("							code += \"<p>BUYER_ADD2     : \" + res.buyer_add2 + \"</p>\";\r\n");
      out.write("							code += \"<p>BUYER_MAIL     : \" + res.buyer_mail + \"</p>\";\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							$('#td2').html(code);\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("						},\r\n");
      out.write("						error : function(xhr){\r\n");
      out.write("							alert(\"상태 : \" + xhr.status);\r\n");
      out.write("						},\r\n");
      out.write("						dataType : 'json'\r\n");
      out.write("					})\r\n");
      out.write("				})\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr){\r\n");
      out.write("				alert(\"상태 : \" + xhr.status);\r\n");
      out.write("			},\r\n");
      out.write("			dataType : 'json'\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table{\r\n");
      out.write("	border: 2px solid orange;\r\n");
      out.write("}\r\n");
      out.write("td{\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#td2{\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	padding-left: 100px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("	<p>\r\n");
      out.write("	</p>\r\n");
      out.write("	\r\n");
      out.write("	<input type=\"button\" value=\"LPROD리스트\" id=\"lprod\">\r\n");
      out.write("	<br><br>\r\n");
      out.write("	<div class=\"result\" id=\"result1\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("	<p>\r\n");
      out.write("	</p>\r\n");
      out.write("	\r\n");
      out.write("	<input type=\"button\" value=\"BUYER리스트\" id=\"buyer\">\r\n");
      out.write("	<br><br>\r\n");
      out.write("	<div class=\"result\" id=\"result2\">\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>거래처이름</td>\r\n");
      out.write("				<td>거래처상세정보</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td id=\"td1\"></td>\r\n");
      out.write("				<td id=\"td2\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
