/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-04-07 00:40:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._0329;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.serializejson.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("	chk = 0;\r\n");
      out.write("	\r\n");
      out.write("	// 데이타 유효성 체크\r\n");
      out.write("	// id\r\n");
      out.write("	$('#uid').on('keyup',function(){\r\n");
      out.write("		idvalue = $(this).val().trim();\r\n");
      out.write("		\r\n");
      out.write("		idreg = /^[a-z][a-zA-Z0-9]{3,14}$/;\r\n");
      out.write("		if(!(idreg.test(idvalue))){\r\n");
      out.write("			$('#idCheck').prop('disabled',true);\r\n");
      out.write("		} else {\r\n");
      out.write("			$('#idCheck').prop('disabled',false);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		regcheck(idreg,idvalue,this);\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$('#uname').on('keyup',function(){\r\n");
      out.write("		namevalue = $(this).val().trim();\r\n");
      out.write("		namereg = /^[가-힣]{2,5}$/\r\n");
      out.write("		\r\n");
      out.write("		regcheck(namereg, namevalue, this);\r\n");
      out.write("		\r\n");
      out.write("// 		if(!(namereg.test(namevalue))){\r\n");
      out.write("// 			$(this).css('border', '3px solid red');\r\n");
      out.write("// 		} else {\r\n");
      out.write("// 			$(this).css('border', '3px solid green');\r\n");
      out.write("// 		}\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$('#pwd').on('keyup',function(){\r\n");
      out.write("		passvalue = $(this).val().trim();\r\n");
      out.write("		passreg = /^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[!@#$%^&*()_+]).{5,12}$/;\r\n");
      out.write("		regcheck(passreg, passvalue, this);\r\n");
      out.write("		\r\n");
      out.write("// 		passreg = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()_+~`\\-={}[\\]:;'\"<>,.?\\\\/])[A-Za-z\\d!@#$%^&*()_+~`\\-={}[\\]:;'\"<>,.?\\\\/]{8,}$/\r\n");
      out.write("// 		regcheck(passreg, passvalue, this);\r\n");
      out.write("		\r\n");
      out.write("		// 전방탐색\r\n");
      out.write("// 		str = [\"1000원\",\"2원\",\"원\",\"5000원\"];\r\n");
      out.write("// 		reg = /.+(?=원)/;\r\n");
      out.write("// 		reg = /(?=.*원)/;\r\n");
      out.write("		\r\n");
      out.write("// 		for(i=0; i < str.length; i++) {\r\n");
      out.write("// 			bb = reg.test(str[i]);\r\n");
      out.write("// 			alert(bb);\r\n");
      out.write("// 		}\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$('#umail').on('keyup',function(){\r\n");
      out.write("		mailvalue = $(this).val().trim();\r\n");
      out.write("		mailreg = /^[a-zA-Z0-9]+@[a-z][0-9a-zA-z]+(\\.[a-zA-Z]+){1,2}$/\r\n");
      out.write("		regcheck(mailreg, mailvalue, this);\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$('#uhp').on('keyup',function(){\r\n");
      out.write("		hpvalue = $(this).val().trim();\r\n");
      out.write("		hpreg = /^[0-9]{2,3}-[0-9]{3,4}-[0-9]{3,4}$/\r\n");
      out.write("		regcheck(hpreg, hpvalue, this);\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	regcheck = function(reg, value, ele){\r\n");
      out.write("		if(!(reg.test(value))){\r\n");
      out.write("			$(ele).css('border', '3px solid red');\r\n");
      out.write("		} else {\r\n");
      out.write("			$(ele).css('border', '3px solid green');\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$('#idCheck').on('click',function(){\r\n");
      out.write("		// 입력한 값을 가져온다.\r\n");
      out.write("		idvalue = $('#uid').val().trim();\r\n");
      out.write("		\r\n");
      out.write("// 		console.log(idvalue);\r\n");
      out.write("		\r\n");
      out.write("		if(idvalue.length < 1 || idvalue == null) {\r\n");
      out.write("			alert(\"id를 입력해주세요.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write(" 			url: '");
      out.print( request.getContextPath());
      out.write("/idCheck.do',\r\n");
      out.write("			type: 'get',\r\n");
      out.write("			data: {\"id\": idvalue},\r\n");
      out.write("			success: function(res){\r\n");
      out.write("// 				alert(res.flag);\r\n");
      out.write("				$('#idspan').text(res.flag).css({'color': 'blue', 'font-size': '0.8em'});\r\n");
      out.write("				chk = 1;\r\n");
      out.write("			},\r\n");
      out.write("			error: function(xhr){\r\n");
      out.write("				alert(\"상태: \" + xhr.status + \"\\ncode : \" + xhr.statusText);\r\n");
      out.write("			},\r\n");
      out.write("			dataType: 'json'\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$('#zipSearch').on('click',function(){\r\n");
      out.write("		window.open(\"zipsearch.jsp\",\"우편번호찾기\",\"width=500 height=500\");\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 우편번호 검색 모달창 실행 - 검색버튼 클릭\r\n");
      out.write("	$('#zip').on('click',function(){\r\n");
      out.write("		dongvalue = $('#dong').val();\r\n");
      out.write("// 		alert(dong);\r\n");
      out.write("		if(dongvalue.length < 1 || dongvalue == null) {\r\n");
      out.write("			alert(\"검색어를 입력해주세요.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: '");
      out.print( request.getContextPath());
      out.write("/zipSearch.do',\r\n");
      out.write("			type: 'post',\r\n");
      out.write("			data: {\"dong\": dongvalue},\r\n");
      out.write("			success: function(res){\r\n");
      out.write("// 				alert(\"성공\");\r\n");
      out.write("				\r\n");
      out.write("				code =\"<table border='1'>\";\r\n");
      out.write("				code += \"<tr><td>우편번호</td><td>주소</td><td>번지</td></tr>\"\r\n");
      out.write("				$(res).each(function(i,v){\r\n");
      out.write("					bunji = v.bunji;\r\n");
      out.write("					// undefined 비교\r\n");
      out.write("					if(typeof bunji == \"undefined\" ) bunji = \"\";\r\n");
      out.write("					\r\n");
      out.write("					code += \"<tr><td>\" + v.zipcode + \"</td>\";\r\n");
      out.write("					code += \"<td>\" + v.sido + \"  \" + v.gugun + \"  \" + v.dong + \"</td>\";\r\n");
      out.write("// 					code += \"<td>\" + v.gugun + \"</td>\";\r\n");
      out.write("// 					code += \"<td>\" + v.dong + \"</td>\";\r\n");
      out.write("					code += \"<td>\" + bunji + \"</td></tr>\";\r\n");
      out.write("				})\r\n");
      out.write("				code += \"</table>\";\r\n");
      out.write("				console.log(code);\r\n");
      out.write("				$('#result1').html(code);\r\n");
      out.write("			},\r\n");
      out.write("			error: function(xhr){\r\n");
      out.write("				alert(\"상태: \" + xhr.status + \"\\ncode : \" + xhr.statusText);\r\n");
      out.write("			},\r\n");
      out.write("			dataType: 'json'\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 결과에서 한 줄을 선택하면(클릭이벤트)\r\n");
      out.write("	$(document).on('click','#result1 tr',function(){\r\n");
      out.write("		zip = $('td:eq(0)', this).text();\r\n");
      out.write("		addr = $('td:eq(1)', this).text();\r\n");
      out.write("		\r\n");
      out.write("		$('#uzip').val(zip);\r\n");
      out.write("		$('#uadd1').val(addr);\r\n");
      out.write("		\r\n");
      out.write("		// 검색내용 삭제\r\n");
      out.write("		$('#dong').val(\"\");\r\n");
      out.write("		$('#result1').empty();\r\n");
      out.write("		\r\n");
      out.write("		// 모달 닫아주기\r\n");
      out.write("		$(\"#zipModal\").modal('hide');\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	$('#register').on('click',function(){\r\n");
      out.write("		\r\n");
      out.write("		// id 중복체크 여부 확인\r\n");
      out.write("		if(chk == 0) {\r\n");
      out.write("			alert(\"id 중복체크를 해주세요!\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		// 입력한 모든 값을 가져온다. - val()\r\n");
      out.write("// 		idval = $('#uid').val().trim();\r\n");
      out.write("// 		passval = $('#pwd').val().trim();\r\n");
      out.write("// 		nameval = $('#uname').val().trim();\r\n");
      out.write("// 		birval = $('#ubir').val().trim();\r\n");
      out.write("// 		hpval = $('#uhp').val().trim();\r\n");
      out.write("// 		mailval = $('#umail').val().trim();\r\n");
      out.write("// 		zipval = $('#uzip').val().trim();\r\n");
      out.write("// 		add1val = $('#uadd1').val().trim();\r\n");
      out.write("// 		add2val = $('#uadd2').val().trim();\r\n");
      out.write("		\r\n");
      out.write("// 		fdata = {\"id\": idval, \r\n");
      out.write("// 				 \"pass\": passval, \r\n");
      out.write("// 				 \"name\": nameval, \r\n");
      out.write("// 				 \"bir\": birval, \r\n");
      out.write("// 				 \"hp\": hpval, \r\n");
      out.write("// 				 \"mail\": mailval,\r\n");
      out.write("// 				 \"zip\": zipval, \r\n");
      out.write("// 				 \"add1\": add1val, \r\n");
      out.write("// 				 \"add2\": add2val\r\n");
      out.write("// 				};\r\n");
      out.write("\r\n");
      out.write("// 		fdata = \"id=\" + idval + \"&name=\" + nameval + \"&pass=\" + passval\r\n");
      out.write("\r\n");
      out.write("		fdata1 = $('form').serialize();\r\n");
      out.write("		fdata2 = $('form').serializeArray();\r\n");
      out.write("		fdata3 = $('form').serializeJSON();\r\n");
      out.write("		\r\n");
      out.write("		console.log(fdata1);\r\n");
      out.write("		console.log(fdata2);\r\n");
      out.write("		console.log(fdata3);\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: '");
      out.print( request.getContextPath());
      out.write("/insert.do',\r\n");
      out.write("			data: fdata3,\r\n");
      out.write("			type: 'post',\r\n");
      out.write("			success: function(res){\r\n");
      out.write("// 				alert(\"가입성공\");\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				$('#joinspan').text(res.cnt).css('color', 'blue');\r\n");
      out.write("			},\r\n");
      out.write("			error: function(xhr){\r\n");
      out.write("				alert(\"상태: \" + xhr.status + \"\\ncode : \" + xhr.statusText);\r\n");
      out.write("			},\r\n");
      out.write("			dataType: 'json'\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("	tr:first-child{\r\n");
      out.write("		background: black;\r\n");
      out.write("		color: white;\r\n");
      out.write("	}\r\n");
      out.write("	#result1 tr:not(:first-child):hover{\r\n");
      out.write("		background: gray;\r\n");
      out.write("	}\r\n");
      out.write("	.borderstyle{\r\n");
      out.write("		border : 2px solid red;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h2>회원가입</h2>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"\" class=\"needs-validation\" novalidate>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"uid\">아이디:</label>\r\n");
      out.write("				<button type=\"button\" id=\"idCheck\" class=\"btn btn-secondary btn-sm\">중복검사</button>\r\n");
      out.write("				<span id=\"idspan\"></span>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"uid\" placeholder=\"Enter userID\" name=\"mem_id\" required>\r\n");
      out.write("				<div class=\"valid-feedback\">Valid.</div>\r\n");
      out.write("				<div class=\"invalid-feedback\">Please fill out this field.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"pwd\">비밀번호:</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"pwd\" placeholder=\"Enter password\" name=\"mem_pass\" required>\r\n");
      out.write("				<div class=\"valid-feedback\">Valid.</div>\r\n");
      out.write("				<div class=\"invalid-feedback\">Please fill out this field.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"uname\">이름:</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"uname\" placeholder=\"Enter username\" name=\"mem_name\" required>\r\n");
      out.write("				<div class=\"valid-feedback\">Valid.</div>\r\n");
      out.write("				<div class=\"invalid-feedback\">Please fill out this field.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"unbir\">생년월일:</label>\r\n");
      out.write("				<input type=\"date\" class=\"form-control\" id=\"ubir\" placeholder=\"Enter userbir\" name=\"mem_bir\" required>\r\n");
      out.write("				<div class=\"valid-feedback\">Valid.</div>\r\n");
      out.write("				<div class=\"invalid-feedback\">Please fill out this field.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"uhp\">전화번호:</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"uhp\" placeholder=\"Enter userhp\" name=\"mem_hp\" required>\r\n");
      out.write("				<div class=\"valid-feedback\">Valid.</div>\r\n");
      out.write("				<div class=\"invalid-feedback\">Please fill out this field.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"umail\">이메일:</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"umail\" placeholder=\"Enter usermail\" name=\"mem_mail\" required>\r\n");
      out.write("				<div class=\"valid-feedback\">Valid.</div>\r\n");
      out.write("				<div class=\"invalid-feedback\">Please fill out this field.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"uzip\">우편번호:</label>\r\n");
      out.write("				<button type=\"button\" id=\"zipSearch\" class=\"btn btn-secondary btn-sm\">검색</button>\r\n");
      out.write("				<button type=\"button\" data-toggle=\"modal\" data-target=\"#zipModal\" class=\"btn btn-secondary btn-sm\">검색modal</button>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"uzip\" placeholder=\"Enter userzip\" name=\"mem_zip\" required>\r\n");
      out.write("				<div class=\"valid-feedback\">Valid.</div>\r\n");
      out.write("				<div class=\"invalid-feedback\">Please fill out this field.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"uadd1\">주소:</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"uadd1\" placeholder=\"Enter useradd1\" name=\"mem_add1\" required>\r\n");
      out.write("				<div class=\"valid-feedback\">Valid.</div>\r\n");
      out.write("				<div class=\"invalid-feedback\">Please fill out this field.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"uadd2\">상세주소:</label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"uadd2\" placeholder=\"Enter useradd2\" name=\"mem_add2\" required>\r\n");
      out.write("				<div class=\"valid-feedback\">Valid.</div>\r\n");
      out.write("				<div class=\"invalid-feedback\">Please fill out this field.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<button type=\"button\" id=\"register\" class=\"btn btn-outline-primary btn-lg\">Submit</button>\r\n");
      out.write("			<span id=\"joinspan\"></span>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("<div class=\"modal\" id=\"zipModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">우편번호 찾기</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("			<p>찾는 동을 입력하세요.</p>\r\n");
      out.write("			<input type=\"text\" id=\"dong\">\r\n");
      out.write("			\r\n");
      out.write("			<input type=\"button\" value=\"검색\" id=\"zip\" class=\"btn btn-info\">\r\n");
      out.write("			<br><br>\r\n");
      out.write("			<div class=\"result\" id=\"result1\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" id=\"send\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
