/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-04-13 02:25:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <!-- 외부 스크립트 순서 중요 -->\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/board.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.serializejson.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("  	*{\r\n");
      out.write("  		box-sizing: border-box;\r\n");
      out.write("  	}\r\n");
      out.write("  	p{\r\n");
      out.write("/*   		border: 1px solid gray; */\r\n");
      out.write("  		margin: 1px;\r\n");
      out.write("  		padding: 3px;\r\n");
      out.write("  		height: auto;\r\n");
      out.write("  	}\r\n");
      out.write("  	.p1{\r\n");
      out.write("  		float : left;\r\n");
      out.write("  		width: 70%;\r\n");
      out.write("  	}\r\n");
      out.write("  	.p2{\r\n");
      out.write("  		float: right;\r\n");
      out.write("  		width: 28%;\r\n");
      out.write("  	}\r\n");
      out.write("  	.p3{\r\n");
      out.write("  		clear: both;\r\n");
      out.write("  	}\r\n");
      out.write("  	input[name=reply]{\r\n");
      out.write("  		height: 54px;\r\n");
      out.write("  		vertical-align: top;\r\n");
      out.write("  	}\r\n");
      out.write("  	#pagelist{\r\n");
      out.write("  		width: 300px;\r\n");
      out.write("  		margin: 0px auto;\r\n");
      out.write("  	}\r\n");
      out.write("  	label{\r\n");
      out.write("  		display: inline-block;\r\n");
      out.write("  		width: 80px;\r\n");
      out.write("  		height: 30px;\r\n");
      out.write("  	}\r\n");
      out.write("  	.reply-body{\r\n");
      out.write("  		background: #f1faad;\r\n");
      out.write("  		border: 1px solid gold;\r\n");
      out.write("  		margin: 1px;\r\n");
      out.write("  		padding: 5px;\r\n");
      out.write("  	}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write("currentPage = 1;\r\n");
      out.write("mypath = '");
      out.print(request.getContextPath());
      out.write("';\r\n");
      out.write("// console.log(mypath);\r\n");
      out.write("\r\n");
      out.write("reply = { }; // 전역객체, 동적으로 속성과 기능을 추가 가능 reply.name = \"\" reply.bonum=31~~\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	$.listPageServer(1);\r\n");
      out.write("	\r\n");
      out.write("	// 이벤트\r\n");
      out.write("	\r\n");
      out.write("	// 다음 클릭\r\n");
      out.write("	$(document).on('click','#next',function(){\r\n");
      out.write("		\r\n");
      out.write("		// modifyForm이 열려 있는지 비교한다.\r\n");
      out.write("		if($('#modifyForm').css('display') != 'none') {\r\n");
      out.write("			// 열려있으면\r\n");
      out.write("			replyReset();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		currentPage = parseInt($('.pageno').last().text().trim()) + 1;\r\n");
      out.write("// 		alert(currentPage);\r\n");
      out.write("		$.listPageServer(currentPage);\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 이전 클릭\r\n");
      out.write("	$(document).on('click','#prev',function(){\r\n");
      out.write("		\r\n");
      out.write("		// modifyForm이 열려 있는지 비교한다.\r\n");
      out.write("		if($('#modifyForm').css('display') != 'none') {\r\n");
      out.write("			// 열려있으면\r\n");
      out.write("			replyReset();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		currentPage = parseInt($('.pageno').first().text().trim()) - 1;\r\n");
      out.write("// 		alert(currentPage);\r\n");
      out.write("		$.listPageServer(currentPage);\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 페이지번호 클릭\r\n");
      out.write("	$(document).on('click','.pageno',function(){\r\n");
      out.write("		\r\n");
      out.write("		// modifyForm이 열려 있는지 비교한다.\r\n");
      out.write("		if($('#modifyForm').css('display') != 'none') {\r\n");
      out.write("			// 열려있으면\r\n");
      out.write("			replyReset();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		currentPage = $(this).text().trim();\r\n");
      out.write("		$.listPageServer(currentPage);\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 검색 search클릭\r\n");
      out.write("	$('#search').on('click',function(){\r\n");
      out.write("		\r\n");
      out.write("		// modifyForm이 열려 있는지 비교한다.\r\n");
      out.write("		if($('#modifyForm').css('display') != 'none') {\r\n");
      out.write("			// 열려있으면\r\n");
      out.write("			replyReset();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.listPageServer(1);\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 글쓰기 data-bs-toggle=\"modal\" data-bs-target=\"#wModal\"\r\n");
      out.write("// 	$('#write').on('click',function(){\r\n");
      out.write("// 		$('#wModal').modal('show');\r\n");
      out.write("// 	})\r\n");
      out.write("	\r\n");
      out.write("	// 글쓰기 모달창에서 send전송 버튼 클릭\r\n");
      out.write("	$('#send').on('click',function(){\r\n");
      out.write("		// 입력한 모든 값을 가져온다.\r\n");
      out.write("		fdata = $('#wform').serializeJSON();\r\n");
      out.write("		\r\n");
      out.write("		console.log(fdata);\r\n");
      out.write("		\r\n");
      out.write("		$('#wform .txt').val(\"\");\r\n");
      out.write("		$('#wModal').modal('hide');\r\n");
      out.write("		\r\n");
      out.write("		// 서버로 전송하기 파라미터 fdata?????\r\n");
      out.write("		$.boardWriteServer(fdata);\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 수정 삭제 등록 댓글수정 댓글삭제, 제목클릭 -- 이벤트\r\n");
      out.write("	$(document).on('click', '.action', function(){\r\n");
      out.write("		vaction = $(this).attr('name');\r\n");
      out.write("		vidx = $(this).attr('idx');\r\n");
      out.write("			\r\n");
      out.write("		if(vaction == \"modify\") {\r\n");
      out.write("// 			alert(vidx + \"번 글을 수정\");\r\n");
      out.write("\r\n");
      out.write("			vmodify = this;\r\n");
      out.write("\r\n");
      out.write("			// 수정할 본문의 내용을 가져온다.\r\n");
      out.write("			vparents = $(this).parents('.card');\r\n");
      out.write("			vtitle = $(vparents).find('a').text().trim();\r\n");
      out.write("			vname = $(vparents).find('#wr').text().trim();\r\n");
      out.write("			vmail = $(vparents).find('#em').text().trim();\r\n");
      out.write("			vp3 = $(vparents).find('.p3').html().trim();\r\n");
      out.write("			\r\n");
      out.write("			cont = vp3.replace(/<br>/g,\"\\n\");\r\n");
      out.write("			\r\n");
      out.write("			// 같은 이름을 html()로 가져오면 첫번째 것만 가져온다.\r\n");
      out.write("			// text()는 모두 가져옴\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			// modal창에 출력한다.\r\n");
      out.write("			$('#mform #writer').val(vname);\r\n");
      out.write("			$('#mform #subject').val(vtitle);\r\n");
      out.write("			$('#mform #mail').val(vmail);\r\n");
      out.write("			$('#mform #content').val(cont);\r\n");
      out.write("			$('#mform #num').val(vidx);\r\n");
      out.write("			\r\n");
      out.write("			// 모달창 띄울거임\r\n");
      out.write("			$('#mModal').modal('show');\r\n");
      out.write("			\r\n");
      out.write("			$('#mform #writer').prop('disabled', true);\r\n");
      out.write("			\r\n");
      out.write("		} else if(vaction == \"delete\") {\r\n");
      out.write("			alert(vidx + \"번 글을 삭제\");\r\n");
      out.write("			$.deleteBoardServer(this);\r\n");
      out.write("			\r\n");
      out.write("		} else if(vaction == \"list\") {\r\n");
      out.write("// 			alert(vidx + \"번 글과 댓글을 모두 보기\");\r\n");
      out.write("			$.replyListServer(this);\r\n");
      out.write("			\r\n");
      out.write("			// 조회수 증가\r\n");
      out.write("// 			vs = $(this).parents('.card').find('#collapse'+vidx).attr('class');\r\n");
      out.write("// 			alert(vs);\r\n");
      out.write("			\r\n");
      out.write("// 			v = $(this).parents('.card').attr('class');\r\n");
      out.write("// 			alert(v);\r\n");
      out.write("			\r\n");
      out.write("			vshow = $(this).attr('aria-expanded');\r\n");
      out.write("// 			alert(vshow);\r\n");
      out.write("			\r\n");
      out.write("			if(vshow == \"true\") {\r\n");
      out.write("				//alert(\"조회수 증가\");\r\n");
      out.write("				$.hitUpdateServer(this);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		} else if(vaction == \"reply\") {\r\n");
      out.write("// 			alert(vidx + \"번 글에 댓글 등록\");\r\n");
      out.write("			\r\n");
      out.write("// 			console.log($(this).prev().val());\r\n");
      out.write("			\r\n");
      out.write("			cont = $(this).prev().val();\r\n");
      out.write("			name1 = String.fromCharCode( parseInt(Math.random()*26 + 65)); // A ~ Z 까지 랜덤 생성\r\n");
      out.write("			name2 = String.fromCharCode( parseInt(Math.random()*26 + 97)); // a ~ z 까지 랜덤 생성\r\n");
      out.write("			name3 = parseInt(Math.random() * 100 + 1);\r\n");
      out.write("			\r\n");
      out.write("			reply.name = name1 + name2 + name3;\r\n");
      out.write("			reply.cont = cont;\r\n");
      out.write("			reply.bonum = vidx;\r\n");
      out.write("			\r\n");
      out.write("			$(this).prev().val(\"\");\r\n");
      out.write("			\r\n");
      out.write("			// 서버로 전송\r\n");
      out.write("			$.replyWriteServer(this);\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			// 댓글 리스트를 출력\r\n");
      out.write("			// 비동기이기떄문에 여기 쓰면 안됨, 결과가 생기기 전에 실행될 수 있음\r\n");
      out.write("// 			$.replyListServer\r\n");
      out.write("		} else if(vaction == \"r_modify\") {\r\n");
      out.write("// 			alert(vidx + \"번 댓글을 수정\");\r\n");
      out.write("\r\n");
      out.write("			// modifyForm이 열려 있는지 비교한다.\r\n");
      out.write("			if($('#modifyForm').css('display') != 'none') {\r\n");
      out.write("				// 열려있으면\r\n");
      out.write("				replyReset();\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// 수정할 내용(원래 내용)을 가져온다.\r\n");
      out.write("			modifycont = $(this).parents('.reply-body').find('.p3').html();\r\n");
      out.write("			\r\n");
      out.write("			// 원래 내용의 <br>태그를 다시 \\n으로 변경 - modifyForm(수정폼)에 출력\r\n");
      out.write("			mcont = modifycont.replace(/<br>/g, \"\\n\");\r\n");
      out.write("			$('#modifyForm textarea').val(mcont)\r\n");
      out.write("			\r\n");
      out.write("			// 수정폼을 p3으로 이동\r\n");
      out.write("// 			$(this).parents('.reply-body').find('.p3').empty();\r\n");
      out.write("			$(this).parents('.reply-body').find('.p3').empty().append($('#modifyForm'));		\r\n");
      out.write("			\r\n");
      out.write("			// 수정폼을 보이기\r\n");
      out.write("			$('#modifyForm').css('display', 'block');\r\n");
      out.write("// 			$('#modifyForm').show();\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		} else if(vaction == \"r_delete\") {\r\n");
      out.write("			alert(vidx + \"번 댓글을 삭제\");\r\n");
      out.write("			$.deleteReplyServer(this);\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	}) // 이벤트 끝\r\n");
      out.write("	\r\n");
      out.write("	replyReset = function(){\r\n");
      out.write("		// p3을 찾는다.\r\n");
      out.write("		vp3 = $('#modifyForm').parent();\r\n");
      out.write("		\r\n");
      out.write("		// 수정폼을 body로 이동시킴(append), 안보이게 설정\r\n");
      out.write("		$('body').append($('#modifyForm'));\r\n");
      out.write("		\r\n");
      out.write("// 		$('#modifyForm').hide();\r\n");
      out.write("		$('#modifyForm').css('display', 'none');\r\n");
      out.write("		\r\n");
      out.write("		// 원래 내용을 p3에 다시 출력\r\n");
      out.write("		$(vp3).html(modifycont);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 댓글 수정창에서 확인 버튼\r\n");
      out.write("	$('#btnok').on('click',function(){\r\n");
      out.write("		// 입력한 내용을 가져온다.\r\n");
      out.write("		modicont = $('#modifyForm textarea').val();\r\n");
      out.write("		\r\n");
      out.write("		// \\n을 <br>로 바꿔준다.\r\n");
      out.write("		modiout = modicont.replace(/\\n/g,\"<br>\");\r\n");
      out.write("		\r\n");
      out.write("		// p3을 찾는다.\r\n");
      out.write("// 		vp3 = $(this).parents($('.p3')); 위에 .p3이 여러개라 안됨\r\n");
      out.write("		vp3 = $('#modifyForm').parent();\r\n");
      out.write("		\r\n");
      out.write("		// modifyForm을 body로 이동 - 안보이게 설정\r\n");
      out.write("		$('body').append($('#modifyForm'));\r\n");
      out.write("		$('#modifyForm').css('display', 'none');\r\n");
      out.write("		\r\n");
      out.write("		// p3에 입력한 내용 출력(<br>태그로 변경된 내용임)\r\n");
      out.write("		// DB에 수정 성공 후 해야함\r\n");
      out.write("// 		$(vp3).html(modiout);\r\n");
      out.write("		\r\n");
      out.write("		reply.renum = vidx;\r\n");
      out.write("		reply.cont = modicont;\r\n");
      out.write("		\r\n");
      out.write("		$.replyUpdateServer(this);\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 댓글 수정창에서 취소 버튼\r\n");
      out.write("	$('#btnreset').on('click',function(){\r\n");
      out.write("		replyReset();\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 글 수정 modal창에서 전송버튼 클릭\r\n");
      out.write("	$('#msend').on('click',function(){\r\n");
      out.write("		fdata = $('#mform').serializeJSON();\r\n");
      out.write("		console.log(fdata);\r\n");
      out.write("		\r\n");
      out.write("		// 서버로 보내기\r\n");
      out.write("		$.boardUpdateServer();\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		// 수정한 내용으로 본문의 내용 화면 바꾸기 - DB에서 update 성공 후에 실행해야함\r\n");
      out.write("		\r\n");
      out.write("		// modal창에 수정한 내용을 가져온다.\r\n");
      out.write("		mwri = $('#mform #writer').val();\r\n");
      out.write("		msub = $('#mform #subject').val();\r\n");
      out.write("		mmail = $('#mform #mail').val();\r\n");
      out.write("		mcon = $('#mform #content').val();\r\n");
      out.write("		\r\n");
      out.write("		mcon = mcon.replaceAll(/\\n/g,\"<br>\")\r\n");
      out.write("		\r\n");
      out.write("		$('#mModal').modal('hide');\r\n");
      out.write("		\r\n");
      out.write("		// 화면(본문의 내용)바꾸기 \r\n");
      out.write("// 		vparents = $(vmodify).parents('.card');\r\n");
      out.write("// 		$(vparents).find('a').text(msub);\r\n");
      out.write("// 		$(vparents).find('#em').text(mmail);\r\n");
      out.write("// 		$(vparents).find('.wp3').html(mcon);\r\n");
      out.write("\r\n");
      out.write("	})\r\n");
      out.write("}) \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("nav a{\r\n");
      out.write("/* 	display: none; 영역없음 아래껀 영역있음*/\r\n");
      out.write("	visibility: hidden;\r\n");
      out.write("}\r\n");
      out.write("#stype {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("}\r\n");
      out.write("#sword{\r\n");
      out.write("	width: 150px;\r\n");
      out.write("}\r\n");
      out.write("label{\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	width: 80px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("}\r\n");
      out.write("#modifyForm{\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"modifyForm\">\r\n");
      out.write("	<textarea rows=\"5\" cols=\"50\"></textarea>\r\n");
      out.write("	<input type=\"button\" value=\"확인\" id=\"btnok\">\r\n");
      out.write("	<input type=\"button\" value=\"취소\" id=\"btnreset\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" value=\"글쓰기\" id=\"write\" data-bs-toggle=\"modal\" data-bs-target=\"#wModal\">\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm navbar-dark bg-dark\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("<!--     <a class=\"navbar-brand\" href=\"javascript:void(0)\">게시판</a> -->\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"mynavbar\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"javascript:void(0)\">Link</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <form class=\"d-flex\">\r\n");
      out.write("      	\r\n");
      out.write("      	<select class=\"form-select\" id=\"stype\">\r\n");
      out.write("		  <option value=\"\">전체</option>\r\n");
      out.write("		  <option value=\"writer\">이름</option>\r\n");
      out.write("		  <option value=\"subject\">제목</option>\r\n");
      out.write("		  <option value=\"content\">내용</option>\r\n");
      out.write("		</select>\r\n");
      out.write("      \r\n");
      out.write("        <input class=\"form-control me-2\" type=\"text\" id=\"sword\" placeholder=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-primary\" type=\"button\" id=\"search\">Search</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"result\" class=\"container mt-3\"></div>\r\n");
      out.write("<br><br>\r\n");
      out.write("<div id=\"pagelist\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- 글쓰기 The Modal -->\r\n");
      out.write("<div class=\"modal\" id=\"wModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">글쓰기</h4>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <form action=\"\" name=\"wform\" id=\"wform\">\r\n");
      out.write("          <label>이름</label>\r\n");
      out.write("          <input type=\"text\" class=\"txt\" name=\"writer\"><br>\r\n");
      out.write("          \r\n");
      out.write("          <label>제목</label>\r\n");
      out.write("          <input type=\"text\" class=\"txt\" name=\"subject\"><br>\r\n");
      out.write("          \r\n");
      out.write("          <label>이메일</label>\r\n");
      out.write("          <input type=\"text\" class=\"txt\" name=\"mail\"><br>\r\n");
      out.write("          \r\n");
      out.write("          <label>비밀번호</label>\r\n");
      out.write("          <input type=\"password\" class=\"txt\" name=\"password\"><br>\r\n");
      out.write("          \r\n");
      out.write("          <label>내용</label><br>\r\n");
      out.write("		  <textarea rows=\"5\" cols=\"40\" class=\"txt\" name=\"content\"></textarea>\r\n");
      out.write("		  <br><br>\r\n");
      out.write("		  <input type=\"button\" value=\"전송\" id=\"send\">\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 글수정 The Modal -->\r\n");
      out.write("<div class=\"modal\" id=\"mModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">글수정</h4>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <form action=\"\" name=\"mform\" id=\"mform\">\r\n");
      out.write("        \r\n");
      out.write("          <input type=\"hidden\" id=\"num\" name=\"num\">\r\n");
      out.write("        \r\n");
      out.write("          <label>이름</label>\r\n");
      out.write("          <input type=\"text\" class=\"txt\" id=\"writer\" name=\"writer\"><br>\r\n");
      out.write("          \r\n");
      out.write("          <label>제목</label>\r\n");
      out.write("          <input type=\"text\" class=\"txt\" id=\"subject\" name=\"subject\"><br>\r\n");
      out.write("          \r\n");
      out.write("          <label>이메일</label>\r\n");
      out.write("          <input type=\"text\" class=\"txt\" id=\"mail\" name=\"mail\"><br>\r\n");
      out.write("          \r\n");
      out.write("          <label>비밀번호</label>\r\n");
      out.write("          <input type=\"password\" class=\"txt\" id=\"password\" name=\"password\" password=\"password\"><br>\r\n");
      out.write("          \r\n");
      out.write("          <label>내용</label><br>\r\n");
      out.write("		  <textarea rows=\"5\" cols=\"40\" class=\"txt\" id=content name=\"content\"></textarea>\r\n");
      out.write("		  <br><br>\r\n");
      out.write("		  <input type=\"button\" value=\"전송\" id=\"msend\">\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
